# Find dependencies (generated by CMakeDeps)
find_package(fmt REQUIRED)
find_package(magic_enum REQUIRED)
find_package(spdlog REQUIRED)
find_package(protobuf REQUIRED)

# Define a function to link dependencies to a target
function(link_dependencies target)
    target_link_libraries(${target} PRIVATE 
        fmt::fmt-header-only 
        magic_enum::magic_enum
        spdlog::spdlog
        protobuf::protobuf
    )
endfunction()